theme = "nightfox"

[editor]
# Allows support for Windows->Linux SSH full color support
true-color = true

# Custom command picker
[keys.normal."#"]
# Allow toggling inlay hints
"i" = ":toggle lsp.display-inlay-hints"
# Allow toggling whitespaces visibility on <Space> + <+> combo
"s" = ":toggle whitespace.render all none"